# letの時
## 予測
forループ内のi には0-9が順番に表示され、forループ外のiはエラーになる。
## 結果&考察
0-9が順に表示されたのち、forループ外のiについてエラーとなった。
理由として、iはforループ内がブロックスコープであり、forループ外から参照することができないため。

# varの時
0-10の値が表示され、エラーとはならなかった。
varで定義した際には関数スコープとなるため、forループ外から参照することが可能となった。

# 何もつけないとき
非staticモードにしてもエラーが止まらなかったため、実行できませんでした。